### ISSUE TITLE
Any 'recipe' lines in metatdata shoudlp match the name attribute

### ISSUE THREAD

**Issue by arieplugge** [xanzy/chef-guard#41]
When there are 'recipe' lines in the metadata.rb file, the recipe is listed with the cookbook name, which must match the attribute "name".
The error message is not indicative for the error:
ERROR: bad gateway
Response: Failed to upload <cookbookname>to the Supermarket: Multipart POST part 'tarball' must contain a README.

**Comment by svanharmelen** [comment]
@arieplugge do you have an example of that? As far as I can tell the only attribute that has any impact on this is the `name` attribute which needs to be correctly set to the name of the cookbook.

**Comment by arieplugge** [comment]
It was in sbp_resolver which was renamed at some point from "resolver" to "sbp_resolver", but in the metatdata.rb the 'recipe' entries were not renamed.
We (Sander Botman and I) changed for instance:
recipe "resolver", "Configures /etc/resolv.conf via attributes"
into
recipe "sbp_resolver", "Configures /etc/resolv.conf via attributes"
The error messages was confusing ...

**Comment by svanharmelen** [comment]
Clear... Closing this one in favour of issue #40 as these are both about the confusing error message returned by Chef-Guard.
