### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bscott** [xanzy/chef-guard#42]
I suggest that we use http://goconvey.co/ for the test coverage.

Any thoughts?

**Comment by svanharmelen** [comment]
Thought about it a little, but I would like to stick with native/default Go tools as much as possible and not introduce any external dependencies.

I know GoConvey can be used with `go test` so for now let's first focus on getting some tests in there (which we really need by now) and maybe at a later stage have a look at GoConvey to see how it can be used with the added (native) tests and what it's added value is once we have some decent coverage.
