### ISSUE TITLE
Not throwing 409 Conflict Error when depends are not frozen

### ISSUE THREAD

**Issue by Tech356** [xanzy/chef-guard#63]
```
$ knife cookbook upload windows
Uploading windows        [1.34.0]                                         
ERROR: Cookbook windows depends on cookbooks which are not currently      
ERROR: being uploaded and cannot be found on the server.                  
ERROR: The missing cookbook(s) are: 'chef_handler' version '>= 0.0.0'     

$ knife cookbook upload chef_handler                
Uploading chef_handler   [1.1.5]                                          
Uploaded 1 cookbook.                                                      

$ knife cookbook upload windows
Uploading windows        [1.34.0]                                         
Uploaded 1 cookbook. 
```

The `chef_handler` is on the chef server but it isn't frozen. Shouldn't I get a 409 Conflict Error error when I try to upload the `windows` cookbook?

**Comment by svanharmelen** [comment]
@Tech356 it should trow an 412 Precondition Failed with some additional detailed info about what exactly failed. But these checks are only done when you upload with `--freeze`. And by the looks of it, you didn't add that parameter to your command.

Also, the way it will check if depends in your metadata are met is by looking for exact depends. So that means something like this:

```
depends  'chef_handler', '= 1.1.5'
depends 'chef_handler', '1.1.5'
```

This makes sense, because if you do not have a strict dependence there is no way to tell what version should actually be frozen. So things like this are ignored:

```
depends  'chef_handler', '>= 1.1.5'
depends 'chef_handler', '> 1.1.5'
```

**Comment by Tech356** [comment]
@svanharmelen Oops. I copied the wrong command. I did actually have a `--freeze` on that last command when I tested it. 

So it won't actually check if `chef_handler` is frozen since the `windows` cookbook only has 

```
depends          'chef_handler'
```

I think it would be nice if chef-guard could throw a warning when it can't verify a dependency. The box in the flow chart that says "Are all my depends frozen?" is also not quite right. It should probably have a note about what types of dependencies it can check.

**Comment by svanharmelen** [comment]
Well... It's kind of hard to change all community cookbooks out there, and it's also hard to use specific pinning (depends) for each and every dependency you have. We assume that all important dependencies for your application stack are in fact pinned on a specific version.

We have an additional foodcritic check that does check this and gives a foodcritic error when yo have non-specific depends in your metadata. I can share that one if you like...

**Comment by Tech356** [comment]
Alright. That seems like a reasonable decision. 

If you could share that foodcritic check, I think it would be useful.

**Comment by svanharmelen** [comment]
I was going to put it in a gist, but it's actually already in the cookbook :smiley: So you just need to add this line to your wrapper cookbook and your good to go:

`default['chef-guard']['config']['default']['includefcs'] = '/opt/chef-guard/cg_foodcritic_tests.rb'`

This should result in this line in your chef-guard.conf:

`includefcs = /opt/chef-guard/cg_foodcritic_tests.rb`

**Comment by Tech356** [comment]
Thanks!
